version: '3.5'

services:
  postgres:
    container_name: fido_demo
    image: postgres
    environment:
      POSTGRES_USER: fido
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
